### ISSUE TITLE
Gravas tuj povi ekserĉi tajpante, sen devi unue alklaki la serĉujon

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#10]
Ŝajnas esti detalo, sed estas ne.

**Comment by yvesnevelsteen** [comment]
Robin: Tio estas tre facile aldonebla, mi ĵus aldonis tion. Ĉu vi povas testi, ĉu ankaŭ bone funkcias ĉe vi?

**Comment by yvesnevelsteen** [comment]
Robin: Kiam mi iras al la paĝo per Android, la serĉujo aŭtomate ricevas fokuson, sed la klavaro ne aperas. Do oni ne povas tuj ektajpi. Mi ne scias, ĉu teĥnike eblas tuj montri ankaŭ la klavaron. Verŝajne ne.

**Comment by yvesnevelsteen** [comment]
Mi ĵus ie legis la jenon: It’s probably good that Mobile WebKit doesn’t support the autofocusattribute as the zooming/keyboard opening would be too in-your-face in most circumstances.

**Comment by RobinvanderVliet** [comment]
Jam solvita por komputiloj. Ne vere eblas por poŝtelefonoj kaj similaj aparatoj.
