### ISSUE TITLE
Lingvo-elekto: defaŭlto estu Esperanto

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#13]
Se aliras la paĝaro ekzemple dano, mi eble ŝatus ke la interfaco aperu en Esperanto, eĉ se la dua agordita retumila lingvo estas la angla. Malmultaj homoj scias kiel agordi lingvojn; gravas prioritatigi Esperanton tiurilate, se ne multaj esperantistoj (= tiuj kiuj ne parolas lingvon en kiu la interfaco ne disponeblas) laŭ mi vidos interfacon en la angla.

**Comment by RobinvanderVliet** [comment]
Solvite, jam antaŭ iom da tempo fakte.
