### ISSUE TITLE
Lingvo-elekto: unue retumila, poste elektita

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#14]
Sendube vi imagas, ke mi uzas Komputekon en Esperanto kaj ne en la franca, eĉ se mi agordis miajn iPad kaj poŝtelefono en tiu lingvo. Multaj e-istoj faras tiajn aferojn; estas ili ja ofte poliglotoj eksperimentemaj. Gravas do laŭ mi:
1)  okaze de unua vizito al la Komputeko-retejo, elekti la interfaclingvon kiu estas agordita en la retumilo (aŭ operaciumo)
2) okaze de posta vizito montri la retejon en la laste uzita interfaclingvo

**Comment by RobinvanderVliet** [comment]
Ĝuste ĉi tiel nun funkcias la lingvo-sistemo. La elektita lingvo estas konservita en la retumilo.
