### ISSUE TITLE
Fonto Komputada Leksikono

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#16]
Mi multe provis solvi tion siatempe, sed neniam trovis kontentigan solvon, pro la nelogika strukturo de KompLeks. Eble ni kopiu ĝin entute al subdosiero de la Komputeko-retejo kaj tie pli strukturigu ĝin por povi al ĝi referenci.

**Comment by yvesnevelsteen** [comment]
Robin: Mi jam havas bonan ideon kiel trakti tion. Mi poste rakontos.

**Comment by RobinvanderVliet** [comment]
Solvita en la lasta versio.
