### ISSUE TITLE
Fontoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#18]
Mi ĵus aldonis Telegramo-n kiel fonton al https://komputeko.net/fontoj.php 

Kiam vi finpretigos la superrigardon de fontoj, ĉu vi povus:
- aŭtomate nombri kiom ofte fonto estas uzata (sumo de mencioj en fonto EO | fonto  2 EO | fonto   3 EO | fonto 4 EO). Inter krampoj aperas la kvanto de fontoj por la alternativaj tradukoj  (sumo de mencioj en fonto EO alternativo 2 kaj EO alternativo 2).
- aŭtomate ordigi la fontojn laŭ ofteco
- uzi longajn nomojn por la fontoj. Kialoj: a) estas pli praktike alklaki fontojn en la retejo kaj precipe en poŝtelefonoj, kiam ili estas pli longaj b) pli klaras pri kio/kiu temas, kiam ni ne uzas mallongigon...

**Comment by RobinvanderVliet** [comment]
Plene farita nun.
