### ISSUE TITLE
Flavigo de priserĉata ŝlosilvorto en la serĉrezultoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#20]
Ĉu vi planas ankaŭ flave indiki kie aperas la ŝlosilvorto ĉe la rezultoj (kiel en la nuna retejo). Ĉu teknike tio eblos laŭ vi?

**Comment by yvesnevelsteen** [comment]
Robin: Ah, mi ankoraŭ ne faris tion. Mi faros.

**Comment by RobinvanderVliet** [comment]
Mi ĵus aldonis ĉi tion. Mi rimarkis, ke tio iom malrapidigas la retejon. Mi poste ankoraŭ vidu, kiel mi povas plibonigi kaj plirapidigi mian kodon.
