### ISSUE TITLE
Fontoj: ligi ankaŭ al anglalingvaj

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#21]
Mankas fontoj por anglalingvaj vortoj. Estus tamen tre interese aldoni ligilojn tie, ne por scii de kie venas la vorto, sed por tiel facile ekscii pri kio ekzakte temas. Ofte ne klaras tio en la angla.

Se iu koncepto ne klaras (kiel 'link rot'), ke oni povu facile kaj rapide aliri priskribon de la koncepto en la angla.

Mi aldonus unuavice ligilojn al Vikipedio/Vikivortaro kaj al komputilaj vortaroj; eble https://techterms.com/browse/ kaj/aŭ https://www.computerhope.com/jargon.htm Se temas pri ĝenerala vorto/koncepto kiu ne aperas en anglalingva komputila vortaro, ankaŭ eblus ligi al https://www.merriam-webster.com ktp

**Comment by yvesnevelsteen** [comment]
Robin: Mi pripensos kiel bone fari tion

**Comment by RobinvanderVliet** [comment]
Fakte estis tre facile aldoni fontojn por la angla. Mi aldonis novajn kolumnojn por tio en la termino-folio, kaj en la fonto-folio mi jam aldonis du fontojn (Wikipedia kaj Merriam Webster).
