### ISSUE TITLE
DB: korektoj kaj aldonoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#22]
YVES ALDONU/OS
assignee 
clear assignee
custom - unuecigi al 'adaptita'?
privilege permeso Telegram

gallery: pripensi ĉu galerio. Eble jes.

remote working distance working telelaboro

**Comment by yvesnevelsteen** [comment]
![image](https://user-images.githubusercontent.com/45429699/74087849-53ce5a80-4a90-11ea-8a99-15bdba9d9d73.png)

**Comment by RobinvanderVliet** [comment]
Korektoj:
"CSS- klaso" estu "CSS-klaso"
"cyrillic letters" estu "Cyrillic letters"
"developper" estu "developer" (dufoje)
"senkontakta paĝado" estu "senkontakta pagado"

**Comment by RobinvanderVliet** [comment]
Kelkfoje alternativa termino estas en la malĝusta kampo. Mi trovis la jenajn okazojn:
O895:P898
O1772:P1772
O3837:P3837
O4338:P4338
O6537:P6537

Se oni movas tiujn ĉelojn 1-foje dekstren, la problemo estas solvita.

**Comment by RobinvanderVliet** [comment]
Mi antaŭe petis, ke oni forigu la vorton "gigibyte" kiel alternativon al "gigabyte". Mi petis tiun forigon, ĉar tiu vorto entute ne ekzistas. Mi vidas, ke ĝi nun estas aldonita en tute nova vico, kun la traduko "gigibajto". Ekzistas nur gigabajtoj kaj gibibajtoj, ne ekzistas gigibajtoj. Ĉu vi povas forigi la vicon kun "gigibyte"?

**Comment by RobinvanderVliet** [comment]
Kaj en la datumbazo troviĝas jam ĉiuj oficialaj unuoj rilate bajtojn. Sed rilate bitojn nur estas registritaj "kilobito". Eble indas ankaŭ registri ĉiujn aliajn oficialajn unuojn:

eo:eksabito, en/nl:exabit, de:Exabit
eo:eksbibito, en/nl:exbibit, de:Exbibit
eo:gibibito, en/nl:gibibit, de:Gibibit
eo:gigabito, en/nl:gigabit, de:Gigabit
eo:jobibito, en/nl:yobibit, de:Yobibit
eo:jotabito, en/nl:yottabit, de:Yottabit
eo:kibibito, en/nl:kibibit, de:Kibibit
eo:mebibito, en/nl:mebibit, de:Mebibit
eo:megabito, en/nl:megabit, de:Megabit
eo:pebibito, en/nl:pebibit, de:Pebibit
eo:petabito, en/nl:petabit, de:Petabit
eo:tebibito, en/nl:tebibit, de:Tebibit
eo:terabito, en/nl:terabit, de:Terabit
eo:zebibito, en/nl:zebibit, de:Zebibit
eo:zetabito, en/nl:zettabit, de:Zettabit

**Comment by RobinvanderVliet** [comment]
La jenaj du esperantigoj por nomoj de programlingvoj mankas en Komputeko. Vortaro.net ja havas ilin:

eo:Lispo, en/nl:Lisp
eo:Fortrano, en/nl:Fortran

**Comment by RobinvanderVliet** [comment]
Terminoj uzataj kiam oni parolas pri procesoroj:

eo:megaherco, en/nl:megahertz
eo:gigaherco, en/nl:gigahertz

**Comment by RobinvanderVliet** [comment]
Aldonindaj evitindaj vortoj sinonimaj al aliaj vortoj:

#326: amplifikatoro (= amplifilo)
#470: asemblero (= asemblilo)
#3707: fajlo (= dosiero)
#4332: haki (= kodumi, kodrompi)
#4389: hardvaro (= aparataro)
#5392: licenco (= permesilo)
#8993: softvaro (= programaro)

Ne forgesu antaŭmeti krisignon por ke ili aperu kiel evitindaj vortoj en la retejo.
