### ISSUE TITLE
Fonto KompLeks

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#24]
Estus bele se vi povus fari listeton de menciitaj KompLeks-fontoj kiuj ne funkcias por ke mi kontrolu enhave. Se eblas facile por vi...

**Comment by yvesnevelsteen** [comment]
Robin: Ĉi tion mi ankoraŭ ne povas facile solvi. La skripto, kiu nun konvertas XLS al JSON, mem enhavas la liston de ligoj inter unuopaj vortoj kaj KompLeks-paĝoj. Tiu listo estu iam en la folio, por ke ĝi estu redaktebla.

**Comment by RobinvanderVliet** [comment]
Dependas je #27. Necesas loko por konservi la KompLeks-ligojn.

**Comment by RobinvanderVliet** [comment]
> Tiu listo estu iam en la folio, por ke ĝi estu redaktebla.

Post reprogramado de la konvert-skripto mi movis la ligilojn al novaj kolumnoj en la termino-folio. Mi klarigis en la vikio kiel tiu nova variablo-sistemo funkcias.
