### ISSUE TITLE
Doni rimarkon/sugeston per alklako de tabelo-ĉeno

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#26]
Robin: Mi pripensis ankaŭ la eblon alklaki tabelo-ĉelon en la Komputeko-retejo, per kiu oni povas sendi rimarkojn/sugestojn al ia administranto panelo.

**Comment by RobinvanderVliet** [comment]
Dependas je #36.

**Comment by RobinvanderVliet** [comment]
Ĉar ankoraŭ ne ekzistas administranto-panelo, mi povus nun programi la formularon tiel, ke la rimarkoj/sugestoj estas senditaj al iu privata grupo/kanalo ĉe Telegramo. @yvesnevelsteen Kion vi pensas pri tiu ideo?

**Comment by yvesnevelsteen** [comment]
Ege plaĉas al mi via propono!

Fernando tion faris ankaŭ por ES; informoj pri novaj uzantoj kaj eventoj
nun aperas en la grupo ES Administraĵoj

Yves

Op zo 16 feb. 2020 om 16:47 schreef Robin van der Vliet <
notifications@github.com>:

**Comment by yvesnevelsteen** [comment]
Jen iom da inspiro

![image](https://user-images.githubusercontent.com/45429699/74612546-8e766980-5106-11ea-8006-9e394db6e35d.png)

**Comment by RobinvanderVliet** [comment]
@yvesnevelsteen Kion vi pensas pri la jena fenestro? Ĝi aperas kiam oni alklakas tabelvicon.

![Ekrankopio de proponita fenestro](https://user-images.githubusercontent.com/692029/75115454-fffe6c80-565e-11ea-9bea-2789384ded06.png)

**Comment by yvesnevelsteen** [comment]
Estus bone se almenaŭ la angla termino aperus tie ankaŭ.

**Comment by RobinvanderVliet** [comment]
Nun aperas la tuta alklakita tabelvico. Kion vi opinias? Ĉi tiel laŭ mi plej klaras por la uzanto.

![Ekrankopio](https://user-images.githubusercontent.com/692029/75116575-1b22a980-566a-11ea-95d8-0fd1ed976301.png)

**Comment by yvesnevelsteen** [comment]
Jes, pli klaras. Sed oni ne sugestas - oni proponas ŝanĝon. Ĉu ne?

**Comment by RobinvanderVliet** [comment]
Mi konsentas, ke "proponi" pli bonas. Mi ŝanĝis la vorton.

La formularo nun tute funkcias.
