### ISSUE TITLE
Datumaro: ekuzi Google Sheets

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#27]
Kion vi nun uzas por redakti la XLS-folion, ĉu LibreOffice aŭ Excel? Verŝajne ankoraŭ daŭros iom da tempo por la kreado de bona kaj profesia administranto-interfaco...

Eble pripensindas intertempe uzi Google Sheets. Oni povus pli facile redakti ĝin kun pluraj personoj samtempe, kaj mi povus pli facile importi Google-dokumenton per aŭtomata skripto

**Comment by yvesnevelsteen** [comment]
Mi alŝutos la Komputeko-datumaron al Google Drive kaj estonte rekte tie ĝisdatigos.

**Comment by RobinvanderVliet** [comment]
Estus bone, se en tiu dosiero estus du malsamaj folioj: unu por ĉiuj terminoj, unu por ĉiuj fontoj.

![Ekzempla ekrankopio](https://user-images.githubusercontent.com/692029/74270489-994a8c00-4d0b-11ea-9de5-14b7017a0e42.png)

Post la kreo de tiu dosiero mi programos la skripton tiel, ke oni povas per unu skripto ĝisdatigi la tutan retejon ene de kelketaj sekundoj.
