### ISSUE TITLE
Portebla versio: restas la menuo sur la ekrano

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#29]
Ĝi malaperu post kiam oni elektas eron. Mi testis sur iPad. Jen:

![6F533A69-8EBB-4C52-B629-8FA5567AAA51](https://user-images.githubusercontent.com/45429699/74316417-c9c90f00-4d79-11ea-9298-73615d6b9542.png)

**Comment by RobinvanderVliet** [comment]
Riparita.
