### ISSUE TITLE
Kontaktformularo

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#31]
Ni ne forgesu aldoni tion, vidu http://www.nevelsteen.info/kontakto

Mi regule ricevas spamon per tiu formularo, gravas do protekti ĝin per Captcha aŭ io tia.

**Comment by RobinvanderVliet** [comment]
Mi finprogramis la kontaktformularon.

Mi ne aldonis al ĝi ion kontraŭspaman, ĉar mi pensas, ke tio ankoraŭ ne vere necesas. Mi kreis tre similan formularon ĉe alia publika retejo, kaj mi neniam ricevis ajnan aŭtomatan spamon per ĝi.

Verŝajne la formularo ĉe via retejo ja estis uzita por sendi spamon, ĉar ĝi estas ofta WordPress-ŝablono, do multaj robotoj rekonas la ŝablonon, kaj povas do uzi ĝin por sendi spamon.

Se iam okazus spamado per la formularo, ni povus tiam aldoni ion kontraŭspaman.
