### ISSUE TITLE
Fontindikoj estu unuecaj en la dosiero, alie la ligiloj ne funkcias

### ISSUE THREAD

**Issue by RobinvanderVliet** [KomputekoNet/Komputeko#35]
Terminoj:
![Terminoj](https://user-images.githubusercontent.com/692029/74387479-eb1d1000-4df8-11ea-9513-103072235f38.png)
("Telegramo" estu tie "TG".)

Fontoj:
![Fontoj](https://user-images.githubusercontent.com/692029/74387486-f53f0e80-4df8-11ea-8797-3dc40fba9537.png)

En la termino-folio oni indiku la fontojn per la mallongigo. La retejo prenas la plenan nomon el la alia folio, kaj tuj ankaŭ la ligilon. Se en la termino-folio aperas fonto, kiu ne estas en la B-kolumno de la fonto-folio, ne aperas ligilo.

**Comment by yvesnevelsteen** [comment]
Mi proponas **simpligi**. Tiuj mallongigoj aperas tie nur, ĉar ili (plej multaj) aperis en la paperaj verkoj 2008 kaj 2012. Kaj ĉar mi eble denove uzus mallongigojn se iam aperus nova papera versio. Mi tamen verŝajne uzus aliajn mallongigojn. Tial eble **ni simple rezignu pri mallongigoj en la Komputeko-retejo**; nur konfuzos vizitantojn.

Ne estas bona kialo (laŭ mi) plu uzi mallongigojn en la datumaro; tial mi fakte unuecigis ĉion al la longaj nomoj. En mia loka Excel aldoni fonton mi povas fari tre rapide, ĉar mi elektas ĝin el falmenuo (aŭ ĝi aperas kiam mi ektajpas ĝin); la fonto-kolumnoj estas tiel agorditaj en Excel, ke ne eblas erare entajpi ion alian ol la fontoj menciitaj en la folio Fontoj. Estas unu el kialoj ke mi provizore preferas loke per Excel ĝisdatigadi la datumaron.

Jen bildo de Komputeko Google Sheets por via informo.

![41B9AC4D-9022-4593-9C23-0E78EF91E480](https://user-images.githubusercontent.com/45429699/74404418-bc1f9200-4e2a-11ea-99e9-eea060e121b5.png)

**Comment by RobinvanderVliet** [comment]
Mi forigis la kolumnon kun mallongigitaj fontindikoj de la fonto-folio. Ĝi ne plu estas uzata en la retejo. La ligiloj nun denove funkcias.
