### ISSUE TITLE
Kolumno por unika identigilo en termino-folio

### ISSUE THREAD

**Issue by RobinvanderVliet** [KomputekoNet/Komputeko#36]
Ĉu vi povas aldoni kolumnon maldekstre de la kolumno "Versio"? En ĝi estu unika identigilo de la vico.

A1: **#**
A2: 1
A3: 2
A4: 3
_ktp._

**Comment by yvesnevelsteen** [comment]
Jes, mi povas fari tion. Mi ja demandas min kio okazos se poste en Excel loke sur mia komputilo mi aldonos vorton (kaj do linion). Kiel fari praktike? Eble mi devos loke ekuzi Access aŭ liberan alternativan programon. Aŭ ni nur proponu tiun eblon post kiam vi kreis adminejon. Ni poste diskutos; nun ne estas tio prioritato.
