### ISSUE TITLE
Donaco-butono Liberapay

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#37]
Mi kreis LiberaPay-konton por mia fonduso Instigo. Estas nova por mi; mi eksperimentas. Ĉu vi povas al la ĉefpaĝo supre de la Komputeko-retejo aldoni butonon kaj ĉi tiun kodon? La nomo de la butono prefere estu ne 'Donate', sed 'Subteni Komputekon'. Eble tiu nomo ŝanĝiĝu laŭ la lingvo; estus logike. Mi povas eventuale krei tian butonon en PhotoShop, vi vidu.

<script src="https://liberapay.com/instigo/widgets/button.js"></script>
<noscript><a href="https://liberapay.com/instigo/donate"><img alt="Donate using Liberapay" src="https://liberapay.com/assets/widgets/donate.svg"></a></noscript>

**Comment by okellogg** [comment]
Ĉu eblus subteni unuopan (neripetan/senabonan) donacon?

**Comment by yvesnevelsteen** [comment]
Saluton Oliver

Tio certe eblas, ekzemple per ĝiro al la konto de Fonduso Instigo.

Informoj aperas en https://instigo.be - mi ilin kopias ĉi tien:

*Eblas ankaŭ donaci monsumon rekte al la bankokonto de la fonduso. Antaŭ ol
fari tion, sciigu al Yves kiun sumon vi ĝiros kaj informu lin, ĉu via ĝiro
koncernas specifan projekton aŭ ne. Jen la necesaj datumoj por tia ĝiro
ekster Liberapay: Verdaj Skoltoj asbl - fonduso Instigo. Rue des Champs 3,
B 5060 Sambreville IBAN : BE25 9731 2584 2982 BIC : ARSPBE22*

Amike

Yves

Op di 17 jan. 2023 om 20:28 schreef Oliver Kellogg ***@***.***
