### ISSUE TITLE
Elekti (mal)kroman lingvon donas strangan rezulton

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#38]
Kiam oni elektas (mal)kroman lingvon, jen rezulto kiu aperas sur la ekrano:

![image](https://user-images.githubusercontent.com/45429699/74452949-07b15a80-4e82-11ea-910a-f90a5107febf.png)

**Comment by RobinvanderVliet** [comment]
Mi jam rimarkis, ke tio okazas, kaj mi pensas, ke mi scias kial. Mi esploros kaj riparos tion.

**Comment by RobinvanderVliet** [comment]
Riparita.
