### ISSUE TITLE
Fontoj: la tria kolumno estas tro larĝa sur poŝtelefono

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#39]
Ĝi estu malpli larĝa, kiel sub Nederlands. Nomoj en la tria kolumno aperu en du aŭ tri linioj sur poŝtelefono.

![DD5B6CD0-E4D6-4DF0-9B56-E1298FC37EAA](https://user-images.githubusercontent.com/45429699/74463175-b7da8f80-4e91-11ea-8a15-8c85374be4e2.jpeg)

**Comment by RobinvanderVliet** [comment]
Ne vere eblas facile eĉ plimallarĝigi la kolumnon, ĉar kelkaj nomoj simple estas tro longaj.

Mi anstataŭe faris ĉi tion: ĉe aparatoj kun malgrandaj ekranoj la priskribo nun aperas sub la aliaj ĉeloj. Tiel aspektas plej bone laŭ mia opinio.

![Ekrankopio de la fonto-tabeloj ĉe malgranda ekrano](https://user-images.githubusercontent.com/692029/75173759-a7e36b00-572f-11ea-9c49-d4f0384ed253.png)

**Comment by yvesnevelsteen** [comment]
Bonega solvo! Dankon, Robin.
