### ISSUE TITLE
Poŝtelefono: post kiam oni elektis (mal)kroman lingvon, malaperu la menuo. Aŭ aperu butono 'Fermi la falmenuon'

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#40]
![5EEA33E1-DD7B-4F69-9056-34A406CBB927](https://user-images.githubusercontent.com/45429699/74464636-2c163280-4e94-11ea-983c-b69f725b215e.jpeg)

**Comment by RobinvanderVliet** [comment]
Mi ne pensas, ke la menuo tuj malaperu, ĉar temas pri menuo kun markobutonoj. Uzantoj eble volas indiki plurajn lingvojn.

Oni jam povas fermi la menuon samkiel oni povas fermi la interfaclingvo-menuon, per reklako sur la butono mem aŭ per klako ie ajn ekster la menuo.
