### ISSUE TITLE
Neologismoj, evitindaj vortoj kaj eĉ eraraj vortoj: kiel trakti ilin?

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#43]
Eblas 'solvi' aldonante "(evitinda)", sed eble ekzistas aliaj solvoj. Mi pensas ekzemple pri la eblo montri 'inteligentan, personigeblan respondon' kiel: 

La vorto 'fajlo' ne ekzistas en Komputeko, car ne temas pri komputila vorto. Ĉu vi celis 'dosiero'?

**Comment by RobinvanderVliet** [comment]
Hodiaŭ mi eksperimentis kaj prilaboris la montradon de evitindaj/malrekomendindaj vortoj. @yvesnevelsteen Kion vi opinias pri la jena solvo:

https://telegramo.org/komputeko/#diĝita
Kiam oni rekte serĉas evitindan vorton, oni vidas ĝin en la listo, sed aperas ruĝa fonkoloro por indiki, ke temas pri evitinda vorto.

https://telegramo.org/komputeko/#cifereca
https://telegramo.org/komputeko/#digital
Kiam oni serĉas sinonimon aŭ tradukon de la evitinda vorto, oni ne vidas la evitindan vorton en la tabelo. Tiumaniere ni evitas, ke homoj uzus ilin. Oni do nur vidas ilin, se oni specife serĉas la evitindan vorton.

En posta fazo, kiam ni havas agordo-paĝon, ni povas aldoni elektilon:
- Montri nur evitindajn vortojn, se oni eksplicite serĉas ilin _(defaŭlte)_
- Ĉiam montri evitindajn vortojn
- Neniam montri evitindajn vortojn

**Comment by yvesnevelsteen** [comment]
Tre inteligenta solvo estas! Mi favoras.

**Comment by yvesnevelsteen** [comment]
Kie/kiel indiki, ke vorto estas evitinda?

**Comment by RobinvanderVliet** [comment]
> Kie/kiel indiki, ke vorto estas evitinda?

En la administranto-panelo estos elektobutono ĉe vorto, per kiu oni povas indiki, ke la vorto estas evitinda. Sed ĉar ni ankoraŭ ne havas la panelon, mi provizore uzas ĉi tiun solvon:

![ekrankopio de folio](https://user-images.githubusercontent.com/692029/76147472-c2590500-609c-11ea-9ca3-ef4d11c55adc.png)
Vi povas aldoni krisignon antaŭ vorto, por indiki, ke la vorto estas evitinda.
