### ISSUE TITLE
Pri la angla en Komputeko: eble ni nur montru vortojn kiuj vere ekzistas

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#44]
Ĉar la angla estas sufiĉe nelogika lingvo, mi sisteme aldonis al Komputeko diversajn "variantojn" de la angla. Ankaŭ erarajn. La celo de tio estas precipe zorgi pri tio, ke iu kiu serĉas vorton, ankaŭ ĝin trovas. Ekzemploj:

**screen font**; "screenfont" ne vere ekzistas, sed aperas en Komputeko
**screenshot**; "screen shot" ne vere ekzistas, sed aperas en Komputeko

Mi pripensis ke estus bone plu ebligi serĉadon, sed tamen ne montri erarojn en la serĉrezultoj. Per Komputeko mi celas malkontribui al erarumado, do la bezono je svaga serĉo (approximate string matching; fuzzy string searching) estas reala.

**Comment by RobinvanderVliet** [comment]
#28 solvus ĉi tiun problemon.

**Comment by RobinvanderVliet** [comment]
https://telegramo.org/komputeko/#cre%20en%20fon
Spacetoj nun estas tute ignoritaj, do ĉi tiu problemo estas solvita. Iam mi plibonigu la serĉsistemon per kreado de pli ampleksa svaga serĉado.
