### ISSUE TITLE
Alklakeblo de fontoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#45]
Mi rimarkis, ke ne ĉiam la fonto Komputada Leksikono estas alklakebla/serĉebla.
Mi imagas, ke ĝi nur estas alklakabla kiam estas 100% kongrua serĉrezulto.
Sed se vi faras tian distingon, estus eble bone indiki diferencon per substreko aŭ alia koloro, ĉu?

Mi proponas, ke alklakeblaj fontoj aperu ĉi tiel:

![image](https://user-images.githubusercontent.com/45429699/74633107-34ef5880-5161-11ea-8bc8-0fd515477aaf.png)

**Comment by RobinvanderVliet** [comment]
Farita. Nun la ligiloj estas bluaj, kaj kiam oni musumas la ligilon, aperas substreko.
