### ISSUE TITLE
Serĉado: neologismoj kaj ne ekzistantaj vortoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#49]
Por tiaj vortoj estus bone, montri tekston

"La vorto 'softvaro' ne ekzistas en Komputeko. Ĉu vi celas 'programaro'?

Kiel realigi ion tiaj praktike? Ĉu mi kreu apartan folion en la datumbazo kun listeto de tiaj vortoj?

**Comment by RobinvanderVliet** [comment]
Duoblaĵo de #43.
