### ISSUE TITLE
Ligiloj al CC en la ĉefpaĝo: ne al la angla, sed al la diversaj lingvoj

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#50]
Ekzistas en multaj lingvoj, ni do nepre ne ligu al la anglalingva paĝo (eĉ se mi konscias ke nur ĝi jure validas)

EO: https://creativecommons.org/licenses/by-sa/4.0/deed.eo

**Comment by RobinvanderVliet** [comment]
> Ekzistas en multaj lingvoj, ni do nepre ne ligu al la anglalingva paĝo

Kompreneble ni ne ligu nur al la anglalingva paĝo. Mi simple ankoraŭ ne programis tion. Mi faros tiel, ke ĝi ligos al la paĝo en kiu oni uzas Komputekon.

> (eĉ se mi konscias ke nur ĝi jure validas)

La jure valida teksto troviĝas ĉe alia paĝo, kaj ĝi ankaŭ disponeblas en multaj lingvoj, sed ne en Esperanto. Vidu sube ĉe https://creativecommons.org/licenses/by-sa/4.0/legalcode

**Comment by RobinvanderVliet** [comment]
Nun parto de la traduk-dosiero, do la interfac-tradukanto povas senprobleme ŝanĝi la ligilon.
