### ISSUE TITLE
Elŝutejo: ĉu vi aldonos?

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#52]
![image](https://user-images.githubusercontent.com/45429699/75604786-d751f900-5adc-11ea-8c58-8c20fc65149e.png)

Poste ni eventuale povus tion aŭtomatigi.

**Comment by RobinvanderVliet** [comment]
Mi aldonos ilin. Eble mi iam povus krei skripton por aŭtomate krei aktualan PDF-dosieron laŭ la elektitaj lingvoj.

**Comment by RobinvanderVliet** [comment]
Aldonite. Mi ankaŭ kreis #61 por posta pripensado pri ĉi tiuj dosieroj.
