### ISSUE TITLE
Cimo pri retrokupla formularo

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#55]
Mi rimarkis, ke eblas alklaki "Versturen" kiam ne estas plenigitaj la kampoj nomo kaj retpoŝtadreso - ne aperas erarmesaĝo kaj ŝajnas ke mesaĝo estas sendita. Sed nenio estas sendita... 

![image](https://user-images.githubusercontent.com/45429699/75771096-8b57bc00-5d49-11ea-8be6-b3396fca8b43.png)

**Comment by RobinvanderVliet** [comment]
Mi ne povas reprodukti ĉi tiun cimon. Kiam mi provas tion mi ricevas mesaĝon, ke mi devas entajpi mian nomon. Eble mi ŝanĝis ion antaŭ kelkaj horoj...

Ĉu vi povas reprovi?
