### ISSUE TITLE
Neniu rezulto - kial aperas tio tute sube?

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#57]
Aperas kiam oni serĉas 'ujo' kaj 'test'. Ne aperas kiam oni serĉas 'screenshot', ekzemple. Strangas.
 
https://telegramo.org/komputeko/#ujo

![image](https://user-images.githubusercontent.com/45429699/75984558-f55b9700-5eea-11ea-874b-d7bd5880bf11.png)

**Comment by RobinvanderVliet** [comment]
Solvite. Post kiam "Neniu rezulto" unufoje montriĝis, la teksto ne plu malaperis post alia serĉo.
