### ISSUE TITLE
Koniga bildo: nova kovrilo

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#58]
Kiam mi konigas la retejon per Facebook, aperas blua kovrilo. Tio estas la malnova, de la verko el 2008. Ĉu vi povas zorgi pri tio ke en la nova retejo aperos tiu de 2012?

![169A58EA-DF72-4D2F-8B16-848C84A97121](https://user-images.githubusercontent.com/45429699/76083763-98c1b000-5fae-11ea-9dbd-2c73aabf21b6.jpeg)

**Comment by RobinvanderVliet** [comment]
@yvesnevelsteen Mi pensas, ke mi solvis ĉi tiun problemon. Ĉu vi povas testi?

**Comment by RobinvanderVliet** [comment]
Mi petis iun testi, kaj ŝajnas al mi, ke la problemo estas solvita.

![ekrankopio de babilejo](https://user-images.githubusercontent.com/692029/76173807-ea329080-61a2-11ea-9626-e7a2d9bdaf3e.png)
