### ISSUE TITLE
Ebligi kopiadon de serĉrezulto sen malfermi formularon

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#59]
Mi regule kopias serĉrezultojn. Sed farante tion, malfermiĝas la retrokupla formularo. Ĝenas.

**Comment by yvesnevelsteen** [comment]
Robin: Eble per butono, per kiu oni povas malfermi la formularon. Tiumaniere ankaŭ pli klaras al uzantoj, ke tiu menuo entute ekzistas/
Yves: ĝuste

**Comment by RobinvanderVliet** [comment]
Solvite.
