### ISSUE TITLE
Fontoj: angla tute suben

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#60]
Mi scias ke alfabete, 'English' aperu antaŭ 'Esperanto', sed ne aspektas serioze nun la fontopaĝo kun indiko de unu angla fonto - Wikipedia. Do bv. ŝovi tion tute suben.

![Screenshot_20200306-193816](https://user-images.githubusercontent.com/45429699/76112476-91b49500-5fe2-11ea-81d9-a8e56c78c1a0.png)

**Comment by RobinvanderVliet** [comment]
Solvite! La lingvoj nun estas ordigitaj laŭ la suma fonto-kvanto. Esperanto aperas tute supre kaj la angla aperas tute sube.
