### ISSUE TITLE
Fonto OpenOffice.org

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#67]
Ĉu vi povas esplori, ĉu eblas rekte traserĉebligi la fonton LibreOffice de la Komputeko-retejo?
https://translations.documentfoundation.org/projects/libo_ui-master/#search

Robin: Mi ankaŭ jam trovis kiel fari ligilon al tiu tradukejo.

**Comment by RobinvanderVliet** [comment]
Farite.
