### ISSUE TITLE
Serĉi triliteraĵojn: ĉu provizore montri 150-200 serĉrezultojn?

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#71]
Eble provizore montru la 150-200 unuajn?
Ankaŭ mi spertis tiun problemon kiam mi serĉis 'set'.

--------- Doorgestuurd bericht --------
Van: Yves Nevelsteen <yves.nevelsteen@gmail.com>
Datum: wo 25 mrt. 2020 om 14:13
Onderwerp: Re: tab en Komputeko
Aan: Bart Demeyere <Bart.Demeyere@esperanto.be>

Jes, mi konscias. 

Robin jam multe plibonigis la retejon, sed tion ne. Estas tamen antaŭvidita.

Ĉu vi jam malkovris la novan betaretejon?

https://telegramo.org/komputeko

Amike

Yves

Op wo 25 mrt. 2020 om 11:05 schreef Bart Demeyere <Bart.Demeyere@esperanto.be>
Yves,

Mi sercxis la Anglan 'tab' en Komputeko. Oni ne povas vidi cxiujn rezultojn (nur la unuaj 100) kaj tab estas inter tiuj nevideblaj.

Bart

**Comment by RobinvanderVliet** [comment]
Mi bezonas altigi ĝin al 300 antaŭ ol "tab" videblas. Mi ĵus faris tion.

Kiam ni havos #62, mi aldonos la eblon agordi kiom da rezultoj maksimume estu videblaj.
