### ISSUE TITLE
Ebligi serĉadon kun kaj sen streketo

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#74]
Kiam mi serĉas "double click" en Komputeko, la rezulto kun streketo ne aperas. Ĉu eblus solvi tion?

Mi tre ŝatus, ke serĉo "ignoru" streketojn samkiel estas ignorataj spacoj inter du vortoj.

**Comment by RobinvanderVliet** [comment]
Farite. Nun ankaŭ streketoj estas ignorataj.
