### ISSUE TITLE
Aŭtomate estu uzata ĉiam la laste uzita interfac-lingvo

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#8]
Per kuketo en la nuna Komputeko-retejo, oni zorgas pri tio ke uzanto nur unufoje devas elekti lingvon de interfaco. Post kiam la lingvo estas elektita, ĉiam aperas la interfaco en tiu lingvo. Evidente devas esti aldonita la eblo ŝanĝi la lingvon.

**Comment by RobinvanderVliet** [comment]
Ĉi tio jam funkcias. Mi konservas la laste agorditan interfac-lingvon (kune kun kelkaj aliaj agordoj) per [loka konservado](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).
