### ISSUE TITLE
Ĉu vi povas aldoni EO-fonton?

### ISSUE THREAD

**Issue by yvesnevelsteen** [KomputekoNet/Komputeko#81]
Mi provlegis **Liberapay** kaj farante tion, kolektis kelkajn novajn vortojn.
Ĉu do vi povas tiun fonton aldoni?

Serĉkodo: https://hosted.weblate.org/translate/liberapay/core/eo/?q=

Ekzemple https://hosted.weblate.org/translate/liberapay/core/eo/?q=wallet

**Comment by RobinvanderVliet** [comment]
Mi aldonis ĝin. Vidu la paĝon kun fontoj.
